import React, { useEffect, useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

const TechnicalMoat: React.FC = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  const cardsRef = useRef<(HTMLDivElement | null)[]>([]);

  const features = [
    {
      title: "Adaptive Difficulty Engine",
      description: "Our proprietary ScreenIQ engine analyzes performance mid-session to evolve questions. If a candidate excels, the logic jumps to high-latency system design hurdles instantly.",
      details: ["Real-time branching", "Complexity scaling", "Non-deterministic logic"],
      metric: "1.2ms Latency"
    },
    {
      title: "Anti-Cheat Neural Link",
      description: "Hardware-level telemetry tracking. We analyze 140+ behavioral signals including keystroke cadence, focus-shifts, and clipboard entropy to flag LLM-usage with 99.9% precision.",
      details: ["Keystroke biometrics", "Tab-switch detection", "Clipboard tracking"],
      metric: "99.9% Precision"
    },
    {
      title: "Mixture-of-Experts (MoE)",
      description: "Assessments are generated by a specialized MoE model that understands the exact architectural patterns of your internal codebase for ultra-specific relevance.",
      details: ["Custom LLM training", "Codebase ingestion", "Stack-specific depth"],
      metric: "8 Expert Sub-nets"
    },
    {
      title: "The Skill Passport",
      description: "A cryptographically signed technical identity. Candidates verify once and carry their 'Verified Engineer' status across the entire RoleScreen ecosystem.",
      details: ["Portable credentials", "Blockchain verification", "One-click trust"],
      metric: "Web3 Verified"
    },
    {
      title: "Fair Play Logic v4.0",
      description: "Our algorithms strip all demographic metadata from the evaluation process. The gate is 100% blind to everything except the raw, functional output of the candidate.",
      details: ["Bias elimination", "Anonymized grading", "Equity auditing"],
      metric: "Zero-Bias Gate"
    },
    {
      title: "Real-time Telemetry Hub",
      description: "Recruiters can watch live code-playbacks with heatmaps showing exactly where candidates struggled, where they excelled, and how they think under pressure.",
      details: ["Code playback", "Struggle heatmaps", "Decision tracing"],
      metric: "120 FPS Replay"
    },
    {
      title: "Global CDN Edge Screening",
      description: "Low-latency assessments served from 300+ global edge locations. Every candidate gets a zero-lag experience, regardless of their geographical coordinates.",
      details: ["Edge computing", "Anycast routing", "V8 Isolate runtime"],
      metric: "<20ms RTT"
    },
    {
      title: "Infrastructure as Assessment",
      description: "We spin up actual ephemeral cloud environments for candidates. They aren't just coding; they are deploying, debugging, and scaling real resources.",
      details: ["Kubernetes isolates", "Terraform hooks", "Live debugging"],
      metric: "Ephemeral Pods"
    },
    {
      title: "Semantic Code Search",
      description: "Recruiters can search their entire talent pool using semantic queries like 'candidates who understand eventual consistency in Go' rather than just 'Go developer'.",
      details: ["Vector embeddings", "Semantic indexing", "NLP retrieval"],
      metric: "Vector Indexed"
    }
  ];

  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger);
    
    const ctx = gsap.context(() => {
      const validCards = cardsRef.current.filter(Boolean);
      if (validCards.length > 0) {
        gsap.fromTo(validCards, 
          { y: 60, opacity: 0 },
          {
            y: 0,
            opacity: 1,
            duration: 0.8,
            stagger: 0.1,
            ease: "power3.out",
            scrollTrigger: {
              trigger: sectionRef.current,
              start: "top 85%",
              toggleActions: "play none none none"
            },
          }
        );
      }
    }, sectionRef);

    const timeout = setTimeout(() => {
      cardsRef.current.forEach(card => {
        if (card) card.style.opacity = "1";
      });
    }, 2000);

    return () => {
      ctx.revert();
      clearTimeout(timeout);
    };
  }, []);

  return (
    <section id="moat" ref={sectionRef} className="py-32 px-6 max-w-7xl mx-auto relative">
      <div className="text-center mb-24">
        <div className="inline-block px-4 py-1 rounded-full border border-white/10 text-[10px] font-black uppercase tracking-[0.4em] text-[#007AFF] mb-6">Deep Infrastructure</div>
        <h2 className="text-5xl md:text-8xl font-black tracking-tighter mb-8 leading-none">The Technical Moat.</h2>
        <p className="text-xl md:text-2xl text-white/40 max-w-3xl mx-auto leading-relaxed">
          While competitors build forms, we build infrastructure. Our platform is the defensive perimeter for your engineering culture.
        </p>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        {features.map((feature, idx) => (
          <div 
            key={idx} 
            ref={el => cardsRef.current[idx] = el}
            className="glass squircle p-8 md:p-10 hover:bg-white/[0.07] transition-all cursor-default group border-white/5 relative overflow-hidden flex flex-col h-full"
            style={{ opacity: 0 }}
          >
            <div className="absolute top-0 right-0 p-6 flex flex-col items-end">
               <div className="text-xs font-black text-[#007AFF] uppercase tracking-widest opacity-30 group-hover:opacity-100 transition-opacity mb-2">{feature.metric}</div>
               <div className="text-4xl text-white/5 font-black group-hover:text-white/10 transition-colors">0{idx + 1}</div>
            </div>
            
            <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-8 group-hover:scale-110 group-hover:bg-[#007AFF]/10 group-hover:border-[#007AFF]/30 transition-all duration-500">
              <div className="w-4 h-4 rounded-full bg-white/20 group-hover:bg-[#007AFF] transition-colors"></div>
            </div>

            <h3 className="text-2xl font-bold mb-4 text-white group-hover:text-[#007AFF] transition-colors">{feature.title}</h3>
            <p className="text-white/50 leading-relaxed text-lg mb-8 flex-grow">{feature.description}</p>
            
            <div className="flex flex-wrap gap-2">
              {feature.details.map((detail, i) => (
                <span key={i} className="text-[9px] font-black uppercase tracking-widest bg-white/5 border border-white/10 px-2 py-1 rounded-md text-white/40 group-hover:text-white/70 group-hover:border-white/20 transition-all">
                  {detail}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default TechnicalMoat;